### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by coommark** [mike442144/seenreq#7]
I'm trying to integrate seenreq with [node-crawler](https://github.com/bda-research/node-crawler), but at this point just setting up seenrq with redis.

Here is my app code:
```
import express from 'express';
var Crawler = require("crawler");
const seenreq = require('seenreq')

const app = express();

app.get('/', (req, res) => {
    res.json("Working...")
})

app.get('/seen', (req, res) => {
    let seen = new seenreq({
        repo:'redis',
        host:'127.0.0.1',
        port:6379,
        clearOnQuit:false
    });

    var url = "http://www.GOOGLE.com";
    seen.exists(url,{
        callback:function(err,result){
            if(err){
                console.error(err);
            }else{
                console.log(result);
            }
        }
    });
})

app.listen(8080, () => console.log('Running on localhost:8080'));
```

When I run and navigate to http://localhost:8080/seen, I get this error:

```
Running on localhost:8080
C:\prod\crawler\node_modules\bluebird\js\main\async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: callback is not a function
    at setByKeys (C:\prod\crawler\node_modules\seenreq\repo.js:66:3)
    at RedisRepo.setByKeys (C:\prod\crawler\node_modules\seenreq-repo-redis\index.js:36:13)
    at getByKeys (C:\prod\crawler\node_modules\seenreq\repo.js:62:11)
    at tryCatcher (C:\prod\crawler\node_modules\bluebird\js\main\util.js:26:23)
    at Promise.successAdapter (C:\prod\crawler\node_modules\bluebird\js\main\nodeify.js:23:30)
    at Promise._settlePromiseAt (C:\prod\crawler\node_modules\bluebird\js\main\promise.js:582:21)
    at Promise._settlePromises (C:\prod\crawler\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\prod\crawler\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\prod\crawler\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\prod\crawler\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Please any help will be very appreciated. Thank you in advance.

**Comment by mike442144** [comment]
Sorry that the module in npmjs is v1.0.0 and the readme default is old,  pls just checkout the new [readme](https://github.com/mike442144/seenreq/tree/1.0.0). That is because we have no huge cases to prove the new version has no bugs. We plan to merge to master when it is well tested. If you have any more questions feel free to post.

**Comment by mike442144** [comment]
it seems that the problem is solved.
